repositories {
 maven {
     url = 'https://api.modrinth.com/maven'
 }
}

 dependencies {
    implementation 'maven.modrinth:abloom-api:y7kgHPBb'
 }


repositories {
maven {
  name = "Illusive Soulworks maven"
  url = "https://maven.theillusivec4.top/"
  }
}

dependencies {
  runtimeOnly "top.theillusivec4.curios:curios-neoforge:9.5.1+1.21.1"
  compileOnly "top.theillusivec4.curios:curios-neoforge:9.5.1+1.21.1:api"
}


