modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="power"
version="1.3.2"
displayName="Keepers of the Stones II"
displayURL="https://modrinth.com/mod/keepers-of-the-stones-2"
logoFile="logo.png"
credits="Created by Auranite Studio"
authors="MagicalAlexey, Spinoraptor, Linnett, Cucuber, Samuelchik, Max_Sleep, Rezolv and many others."
description="Keepers of the Stones II is a mod created as a continuation of the original version of the Keepers of the Stones mod. It adds more new elemental stones that can be used to improve the character skills and powers."

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "power.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.power]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.215,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.power]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.power]]
    modId="curios"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power]]
    modId="abloom"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.power]]
    modId="abloom_api"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power]]
    modId="curios_api"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power]]
    modId="bettercombat"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power]]
    modId="patchouli"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.power]]
    modId="cpapi"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration