### Particle Image Function
### Version: 1.0.4
### Width: 16
### Height: 16
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~0.875 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~0.875 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~0.875 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~0.875 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~0.75 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~0.75 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.81,0.81,0.81],scale:1} ~0.75 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.75 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.75 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.75 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~0.75 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~0.625 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.71,0.71,0.71],scale:1} ~0.625 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.81,0.81,0.81],scale:1} ~0.625 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.625 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.625 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.00,1.00,1.00],scale:1} ~0.625 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.625 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~0.625 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~0.5 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.81,0.81,0.81],scale:1} ~0.5 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.36,0.36,0.36],scale:1} ~0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.36,0.36,0.36],scale:1} ~0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.00,1.00,1.00],scale:1} ~0.5 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.5 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.5 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~0.5 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~0.375 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.81,0.81,0.81],scale:1} ~0.375 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.375 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.36,0.36,0.36],scale:1} ~0.375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.36,0.36,0.36],scale:1} ~0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.375 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.81,0.81,0.81],scale:1} ~0.375 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~0.375 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~0.25 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.81,0.81,0.81],scale:1} ~0.25 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.25 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.00,1.00,1.00],scale:1} ~0.25 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.81,0.81,0.81],scale:1} ~0.25 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.71,0.71,0.71],scale:1} ~0.25 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~0.25 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~0.125 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.71,0.71,0.71],scale:1} ~0.125 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.125 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0.125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.81,0.81,0.81],scale:1} ~0.125 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.71,0.71,0.71],scale:1} ~0.125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~0.125 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~0.125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~0 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.71,0.71,0.71],scale:1} ~0 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~0 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.71,0.71,0.71],scale:1} ~0 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~0 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~-0.125 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~-0.125 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.81,0.81,0.81],scale:1} ~-0.125 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~-0.125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~-0.125 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~-0.25 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~-0.25 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.71,0.71,0.71],scale:1} ~-0.25 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.91,0.91,0.91],scale:1} ~-0.25 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~-0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~-0.375 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~-0.375 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.81,0.81,0.81],scale:1} ~-0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~-0.375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~-0.5 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~-0.5 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.71,0.71,0.71],scale:1} ~-0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~-0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~-0.625 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.58,0.58,0.58],scale:1} ~-0.625 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.71,0.71,0.71],scale:1} ~-0.625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~-0.625 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~-0.75 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~-0.75 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~-0.75 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.46,0.46],scale:1} ~-0.75 ~0 ~0.125 0 0 0 0 1 force @a
