### Particle Image Function
### Version: 1.0.4
### Width: 16
### Height: 16
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~0.75 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~0.75 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~0.625 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.76,0.88,0.85],scale:1} ~0.625 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~0.625 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~0.5 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.89,0.95,0.92],scale:1} ~0.5 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~0.5 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~0.375 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.89,0.95,0.92],scale:1} ~0.375 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~0.375 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~0.375 ~0 ~0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~0.25 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.89,0.95,0.92],scale:1} ~0.25 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.62,0.79,0.79],scale:1} ~0.25 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~0.25 ~0 ~0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~0.125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.76,0.88,0.85],scale:1} ~0.125 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.89,0.95,0.92],scale:1} ~0.125 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.62,0.79,0.79],scale:1} ~0.125 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~0.125 ~0 ~0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~0 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.76,0.88,0.85],scale:1} ~0 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.89,0.95,0.92],scale:1} ~0 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~0 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~0 ~0 ~0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.125 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.76,0.88,0.85],scale:1} ~-0.125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.00,1.00,1.00],scale:1} ~-0.125 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.76,0.88,0.85],scale:1} ~-0.125 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.125 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~-0.125 ~0 ~0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.76,0.88,0.85],scale:1} ~-0.25 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.00,1.00,1.00],scale:1} ~-0.25 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.76,0.88,0.85],scale:1} ~-0.25 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.62,0.79,0.79],scale:1} ~-0.25 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~-0.25 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.375 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.375 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.375 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.375 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.76,0.88,0.85],scale:1} ~-0.375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.76,0.88,0.85],scale:1} ~-0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.00,1.00,1.00],scale:1} ~-0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.76,0.88,0.85],scale:1} ~-0.375 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.62,0.79,0.79],scale:1} ~-0.375 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.375 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~-0.375 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.5 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.76,0.88,0.85],scale:1} ~-0.5 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.89,0.95,0.92],scale:1} ~-0.5 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.89,0.95,0.92],scale:1} ~-0.5 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.89,0.95,0.92],scale:1} ~-0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.89,0.95,0.92],scale:1} ~-0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.89,0.95,0.92],scale:1} ~-0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.76,0.88,0.85],scale:1} ~-0.5 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.62,0.79,0.79],scale:1} ~-0.5 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.5 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~-0.5 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~-0.625 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~-0.625 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.625 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.62,0.79,0.79],scale:1} ~-0.625 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.62,0.79,0.79],scale:1} ~-0.625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.625 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.49,0.66,0.69],scale:1} ~-0.625 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~-0.625 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~-0.625 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~-0.75 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~-0.75 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~-0.75 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~-0.75 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.50,0.58],scale:1} ~-0.75 ~0 ~0.125 0 0 0 0 1 force @a
