### Particle Image Function
### Version: 1.0.4
### Width: 16
### Height: 16
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.875 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.875 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.875 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.875 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.75 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.63,0.85,0.96],scale:1} ~0.75 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.63,0.85,0.96],scale:1} ~0.75 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.68,0.89],scale:1} ~0.75 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~0.75 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.625 ~0 ~-0.875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.625 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.63,0.85,0.96],scale:1} ~0.625 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.82,0.98,1.00],scale:1} ~0.625 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.625 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~0.625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.625 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.5 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.68,0.89],scale:1} ~0.5 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.5 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.51,0.81],scale:1} ~0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.5 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.51,0.81],scale:1} ~0.5 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~0.5 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~0.375 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~0.375 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~0.375 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.125 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.125 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0.125 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~0.125 ~0 ~0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0 ~0 ~-0.875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.63,0.85,0.96],scale:1} ~0 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.63,0.85,0.96],scale:1} ~0 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.68,0.89],scale:1} ~0 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~0 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~0 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~-0.125 ~0 ~-0.875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.63,0.85,0.96],scale:1} ~-0.125 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.82,0.98,1.00],scale:1} ~-0.125 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~-0.125 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.125 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~-0.125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.63,0.85,0.96],scale:1} ~-0.125 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.63,0.85,0.96],scale:1} ~-0.125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.63,0.85,0.96],scale:1} ~-0.125 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.125 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~-0.25 ~0 ~-0.875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.68,0.89],scale:1} ~-0.25 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~-0.25 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.51,0.81],scale:1} ~-0.25 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.25 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~-0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.63,0.85,0.96],scale:1} ~-0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.82,0.98,1.00],scale:1} ~-0.25 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.82,0.98,1.00],scale:1} ~-0.25 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.63,0.85,0.96],scale:1} ~-0.25 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.68,0.89],scale:1} ~-0.25 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.25 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.375 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.375 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.375 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~-0.375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.63,0.85,0.96],scale:1} ~-0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.82,0.98,1.00],scale:1} ~-0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.82,0.98,1.00],scale:1} ~-0.375 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~-0.375 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.51,0.81],scale:1} ~-0.375 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.375 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~-0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.63,0.85,0.96],scale:1} ~-0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.63,0.85,0.96],scale:1} ~-0.5 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~-0.5 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.26,0.37,0.74],scale:1} ~-0.5 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.51,0.81],scale:1} ~-0.5 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.5 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.625 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.625 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.46,0.68,0.89],scale:1} ~-0.625 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.51,0.81],scale:1} ~-0.625 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.51,0.81],scale:1} ~-0.625 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.625 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.75 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.75 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.20,0.26,0.67],scale:1} ~-0.75 ~0 ~0.375 0 0 0 0 1 force @a
