### Particle Image Function
### Version: 1.0.4
### Width: 16
### Height: 16
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust{color:[1.00,1.00,1.00],scale:1} ~0.875 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.00,1.00,1.00],scale:1} ~0.875 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.85,0.94,0.95],scale:1} ~0.75 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.85,0.94,0.95],scale:1} ~0.75 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.00,1.00,1.00],scale:1} ~0.625 ~0 ~0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.74,0.85,0.89],scale:1} ~0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.74,0.85,0.89],scale:1} ~0.5 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.85,0.94,0.95],scale:1} ~0.5 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.34,0.64,0.04],scale:1} ~0.375 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.52,0.79,0.11],scale:1} ~0.375 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.60,0.73,0.81],scale:1} ~0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.52,0.79,0.11],scale:1} ~0.25 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.34,0.64,0.04],scale:1} ~0.25 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.53,0.00,0.18],scale:1} ~0.25 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.53,0.00,0.18],scale:1} ~0.25 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.53,0.00,0.18],scale:1} ~0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.74,0.85,0.89],scale:1} ~0.25 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.00,1.00,1.00],scale:1} ~0.25 ~0 ~0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.34,0.64,0.04],scale:1} ~0.125 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.15,0.47,0.01],scale:1} ~0.125 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.32,0.07,0.00],scale:1} ~0.125 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.00,0.44,0.39],scale:1} ~0.125 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.73,0.03,0.15],scale:1} ~0.125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.73,0.03,0.15],scale:1} ~0.125 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.53,0.00,0.18],scale:1} ~0.125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.60,0.73,0.81],scale:1} ~0.125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.85,0.94,0.95],scale:1} ~0.125 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.32,0.07,0.00],scale:1} ~0 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.51,0.09,0.02],scale:1} ~0 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.00,0.74,0.68],scale:1} ~0 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.00,0.44,0.39],scale:1} ~0 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.87,0.09,0.15],scale:1} ~0 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.53,0.00,0.18],scale:1} ~0 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.40,0.00,0.21],scale:1} ~-0.125 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.00,0.44,0.39],scale:1} ~-0.125 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.00,0.74,0.68],scale:1} ~-0.125 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.87,0.09,0.15],scale:1} ~-0.125 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.73,0.03,0.15],scale:1} ~-0.125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.97,0.29,0.25],scale:1} ~-0.125 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.87,0.09,0.15],scale:1} ~-0.125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.53,0.00,0.18],scale:1} ~-0.125 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.74,0.85,0.89],scale:1} ~-0.125 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.40,0.00,0.21],scale:1} ~-0.25 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.73,0.03,0.15],scale:1} ~-0.25 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.87,0.09,0.15],scale:1} ~-0.25 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.73,0.03,0.15],scale:1} ~-0.25 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.87,0.09,0.15],scale:1} ~-0.25 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.97,0.29,0.25],scale:1} ~-0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.73,0.03,0.15],scale:1} ~-0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.53,0.00,0.18],scale:1} ~-0.25 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.40,0.00,0.21],scale:1} ~-0.375 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.53,0.00,0.18],scale:1} ~-0.375 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.73,0.03,0.15],scale:1} ~-0.375 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.73,0.03,0.15],scale:1} ~-0.375 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.73,0.03,0.15],scale:1} ~-0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.87,0.09,0.15],scale:1} ~-0.375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.73,0.03,0.15],scale:1} ~-0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.40,0.00,0.21],scale:1} ~-0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.40,0.00,0.21],scale:1} ~-0.5 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.40,0.00,0.21],scale:1} ~-0.5 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.53,0.00,0.18],scale:1} ~-0.5 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.73,0.03,0.15],scale:1} ~-0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.73,0.03,0.15],scale:1} ~-0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.40,0.00,0.21],scale:1} ~-0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.40,0.00,0.21],scale:1} ~-0.625 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.40,0.00,0.21],scale:1} ~-0.625 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.40,0.00,0.21],scale:1} ~-0.625 ~0 ~-0.125 0 0 0 0 1 force @a
