### Particle Image Function
### Version: 1.0.4
### Width: 16
### Height: 16
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust 0.42 0.13 0.61 1 ~1 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~1 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0.875 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.82 0.32 0.89 1 ~0.875 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0.875 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0.75 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.82 0.32 0.89 1 ~0.75 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~0.75 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0.625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.82 0.32 0.89 1 ~0.625 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.98 0.5 0.96 1 ~0.625 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~0.625 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.63 0.21 0.76 1 ~0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 1 0.73 0.93 1 ~0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~0.5 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0.375 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.63 0.21 0.76 1 ~0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 1 0.73 0.93 1 ~0.375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.98 0.5 0.96 1 ~0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0.25 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.63 0.21 0.76 1 ~0.25 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 1 0.73 0.93 1 ~0.25 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.98 0.5 0.96 1 ~0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.82 0.32 0.89 1 ~0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0.25 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0.25 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0.25 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0.25 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0.125 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust 1 0.73 0.93 1 ~0.125 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 1 0.73 0.93 1 ~0.125 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 1 1 1 1 ~0.125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 1 1 1 1 ~0.125 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 1 0.73 0.93 1 ~0.125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 1 0.73 0.93 1 ~0.125 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.98 0.5 0.96 1 ~0.125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.98 0.5 0.96 1 ~0.125 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0.125 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust 0.98 0.5 0.96 1 ~0 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 1 0.73 0.93 1 ~0 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 1 0.73 0.93 1 ~0 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 1 1 1 1 ~0 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 1 1 1 1 ~0 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 1 0.73 0.93 1 ~0 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 1 0.73 0.93 1 ~0 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.82 0.32 0.89 1 ~0 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~0 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~-0.125 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~-0.125 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~-0.125 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~-0.125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.63 0.21 0.76 1 ~-0.125 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.82 0.32 0.89 1 ~-0.125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.98 0.5 0.96 1 ~-0.125 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.63 0.21 0.76 1 ~-0.125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~-0.125 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~-0.25 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.82 0.32 0.89 1 ~-0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 1 0.73 0.93 1 ~-0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.63 0.21 0.76 1 ~-0.25 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.13 0.61 1 ~-0.25 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~-0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.98 0.5 0.96 1 ~-0.375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.63 0.21 0.76 1 ~-0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~-0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~-0.5 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.82 0.32 0.89 1 ~-0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.63 0.21 0.76 1 ~-0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~-0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~-0.625 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.63 0.21 0.76 1 ~-0.625 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~-0.625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~-0.75 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.63 0.21 0.76 1 ~-0.75 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~-0.75 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~-0.875 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.21 0.07 0.45 1 ~-0.875 ~0 ~-0.375 0 0 0 0 1 force @a
