### Particle Image Function
### Version: 1.0.4
### Width: 16
### Height: 16
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust 0.56 0.06 0.14 1 ~0.875 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~0.875 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~0.75 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.12 0.12 1 ~0.75 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~0.75 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~0.625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.91 0.39 0.31 1 ~0.625 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~0.625 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.81 0.24 0.2 1 ~0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.81 0.24 0.2 1 ~0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~0.5 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.81 0.24 0.2 1 ~0.375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.12 0.12 1 ~0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~0.25 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.81 0.24 0.2 1 ~0.25 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.81 0.24 0.2 1 ~0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.12 0.12 1 ~0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.12 0.12 1 ~0.25 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~0.25 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~0.125 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.81 0.24 0.2 1 ~0.125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.91 0.39 0.31 1 ~0.125 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~0.125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.12 0.12 1 ~0.125 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~0.125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~0 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.81 0.24 0.2 1 ~0 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 1 0.87 0.82 1 ~0 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.63 0.55 1 ~0 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~0 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~0 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.12 0.12 1 ~0 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~0 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~-0.125 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.81 0.24 0.2 1 ~-0.125 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.63 0.55 1 ~-0.125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.63 0.55 1 ~-0.125 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~-0.125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~-0.125 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.12 0.12 1 ~-0.125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~-0.125 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~-0.25 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.81 0.24 0.2 1 ~-0.25 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.91 0.39 0.31 1 ~-0.25 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.63 0.55 1 ~-0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~-0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~-0.25 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.81 0.24 0.2 1 ~-0.25 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~-0.25 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~-0.375 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.12 0.12 1 ~-0.375 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.81 0.24 0.2 1 ~-0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.91 0.39 0.31 1 ~-0.375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~-0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.12 0.12 1 ~-0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.81 0.24 0.2 1 ~-0.375 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~-0.375 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.06 0.14 1 ~-0.5 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.12 0.12 1 ~-0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.12 0.12 1 ~-0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.81 0.24 0.2 1 ~-0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.81 0.24 0.2 1 ~-0.5 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~-0.5 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~-0.625 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~-0.625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~-0.625 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.39 0.02 0.15 1 ~-0.625 ~0 ~0.125 0 0 0 0 1 force @a
