### Particle Image Function
### Version: 1.0.4
### Width: 16
### Height: 16
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust 0.57 0.72 0.57 1 ~0.625 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0.625 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0.625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0.625 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0.625 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0.625 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0.5 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.73 0.82 0.71 1 ~0.5 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.73 0.82 0.71 1 ~0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.73 0.82 0.71 1 ~0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.73 0.82 0.71 1 ~0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.73 0.82 0.71 1 ~0.5 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.73 0.82 0.71 1 ~0.5 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0.5 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0.375 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0.375 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.35 0.54 0.45 1 ~0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.35 0.54 0.45 1 ~0.375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.35 0.54 0.45 1 ~0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.35 0.54 0.45 1 ~0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0.375 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0.375 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.45 0.62 0.51 1 ~0.25 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.15 0.36 0.3 1 ~0.25 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.15 0.36 0.3 1 ~0.25 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.15 0.36 0.3 1 ~0.25 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.15 0.36 0.3 1 ~0.25 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.45 0.62 0.51 1 ~0.25 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.35 0.54 0.45 1 ~0.125 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.15 0.36 0.3 1 ~0.125 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.15 0.36 0.3 1 ~0.125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.45 0.62 0.51 1 ~0.125 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.45 0.62 0.51 1 ~0.125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.15 0.36 0.3 1 ~0.125 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.15 0.36 0.3 1 ~0.125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.35 0.54 0.45 1 ~0.125 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.35 0.54 0.45 1 ~0 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.15 0.36 0.3 1 ~0 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.15 0.36 0.3 1 ~0 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~0 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.35 0.54 0.45 1 ~0 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.35 0.54 0.45 1 ~-0.125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.45 0.62 0.51 1 ~-0.125 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.45 0.62 0.51 1 ~-0.125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.35 0.54 0.45 1 ~-0.125 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~-0.375 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.73 0.82 0.71 1 ~-0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~-0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~-0.375 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.57 0.72 0.57 1 ~-0.5 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.35 0.54 0.45 1 ~-0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.35 0.54 0.45 1 ~-0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.35 0.54 0.45 1 ~-0.5 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.45 0.62 0.51 1 ~-0.625 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.45 0.62 0.51 1 ~-0.625 ~0 ~0.25 0 0 0 0 1 force @a
