### Particle Image Function
### Version: 1.0.4
### Width: 16
### Height: 16
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust 0.68 0.47 0.35 1 ~0.625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.68 0.47 0.35 1 ~0.625 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.68 0.47 0.35 1 ~0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.86 0.77 0.59 1 ~0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.68 0.47 0.35 1 ~0.5 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.68 0.47 0.35 1 ~0.375 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.98 0.87 1 ~0.375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0.26 0.2 1 ~0.375 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.68 0.47 0.35 1 ~0.25 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~0.25 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.98 0.87 1 ~0.25 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.79 0.65 0.48 1 ~0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.98 0.87 1 ~0.25 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~0.25 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0.26 0.2 1 ~0.25 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.68 0.47 0.35 1 ~0.125 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~0.125 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~0.125 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~0.125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.98 0.87 1 ~0.125 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~0.125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~0.125 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.52 0.38 1 ~0.125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~0.125 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.16 0.13 1 ~0.125 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.68 0.47 0.35 1 ~0 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust 0.86 0.77 0.59 1 ~0 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.98 0.87 1 ~0 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~0 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.79 0.65 0.48 1 ~0 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~0 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.98 0.87 1 ~0 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.86 0.77 0.59 1 ~0 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~0 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~0 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0.26 0.2 1 ~0 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.16 0.13 1 ~0 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust 0.68 0.47 0.35 1 ~-0.125 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~-0.125 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust 0.86 0.77 0.59 1 ~-0.125 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~-0.125 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.98 0.87 1 ~-0.125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~-0.125 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.86 0.77 0.59 1 ~-0.125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~-0.125 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~-0.125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.52 0.38 1 ~-0.125 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~-0.125 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.16 0.13 1 ~-0.125 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0.26 0.2 1 ~-0.25 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~-0.25 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~-0.25 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.98 0.87 1 ~-0.25 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~-0.25 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.86 0.77 0.59 1 ~-0.25 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~-0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~-0.25 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~-0.25 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~-0.25 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0.26 0.2 1 ~-0.25 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.16 0.13 1 ~-0.25 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0.26 0.2 1 ~-0.375 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~-0.375 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.89 0.72 1 ~-0.375 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.86 0.77 0.59 1 ~-0.375 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~-0.375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.52 0.38 1 ~-0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~-0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~-0.375 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0.26 0.2 1 ~-0.375 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.16 0.13 1 ~-0.375 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.16 0.13 1 ~-0.5 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.16 0.13 1 ~-0.5 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0.26 0.2 1 ~-0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~-0.5 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.39 0.29 1 ~-0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0.26 0.2 1 ~-0.5 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.16 0.13 1 ~-0.5 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.16 0.13 1 ~-0.5 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.16 0.13 1 ~-0.625 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.16 0.13 1 ~-0.625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.16 0.13 1 ~-0.625 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.16 0.13 1 ~-0.625 ~0 ~0.125 0 0 0 0 1 force @a
